[draft] Add initial types to allow a basic AWS Step Functions definition
serverless/typescript pull request #39
Opened 2021-04-09 08:19 UTC by aliclark

This PR aims to add definitions for the `serverless-step-functions` plugin which is the defacto way to use AWS Step Functions with Serverless Framework.

The definitions are currently very incomplete, so this will need further work before it can be merged.

2021-04-18 15:33 UTC, fredericbarthelet commented
Hi @aliclark and thanks for your contribution :)

Please note that, as stated in the [Contribution guildelines](https://github.com/serverless/typescript#contributing), any modification made to the `index.d.ts` definition file of this repository is useless - the purpose of this repository is to generate those definition automatically from JSON schema validation constraints within the Serverless Framework. Your modifications would be removed on the next version release.

In order to implement definitions from https://github.com/serverless-operations/serverless-step-functions plugin within this package, one way could simply be to add dependency to this specific plugin in https://github.com/serverless/typescript/blob/b9825f6a5d5c2923282043ff3647ad4bdeb83afc/serverless.yml#L6-L7

One downside of such implementation is the lack of constraint for this plugin to be referenced in your `serverless.yml` before being able to leverage definitions specifics to the plugin. Do you have any idea to enforce such behavior ?

✅ Validation with correct types
```typescript
const serviceFile: AWS = {
  service: 'my-app'

  plugins: ['serverless-step-functions']

  // It's ok to write those properties as the plugin is referenced above
  stepFunctions: {
    stateMachines: //...
}
```

❌ Validation with incorrect types
```typescript
const serviceFile: AWS = {
  service: 'my-app'

  plugins: ['another-plugin']

  // Should not allow those properties, as serverless-step-functions is not referenced in plugins property
  stepFunctions: {
    stateMachines: //...
}
```

In addition, as you can see within the plugin source code in https://github.com/serverless-operations/serverless-step-functions/blob/e0a391d531b2868f5b03fd8eeede3d9073735efa/lib/index.js#L145-L161 , the definition provided to `defineTopLevelProperty` is very simple, and does not cover the various keys allowed within the plugin. This definition shall first be improved before benefiting for the Typescript type auto-generation of this repository.

Do you think you could help first on plugin side to improved JSON schema definitions of `serverless-step-functions` plugin ?

2021-04-18 15:35 UTC, fredericbarthelet commented on index.d.ts
> +  stepFunctions?: {
See https://github.com/serverless/typescript#contributing
All modifications made to `index.d.ts` will be overwritten at each release of this package. No modification shall be done manually to this file.

2021-04-18 15:35 UTC, fredericbarthelet requested changes
See https://github.com/serverless/typescript#contributing
All modifications made to index.d.ts will be overwritten at each release of this package. No modification shall be done manually to this file.

2021-04-21 20:26 UTC, aliclark commented
Hi @fredericbarthelet thanks for the super helpful response!

I think it's a good idea to look at the JSON schema if TypeScript definitions can be generated from it. I'm afraid I don't have much time to spare at the moment so this may be a few months away. Feel free to close the PR if you don't want it to be open during this time.

On the plugins list-dependent checking, I'm afraid I don't think it's possible, since the only think TypeScript would know about this is that plugins has type `string[]` and it won't be able to do anything more specific than that, but *could* do a first pass to check the array contents with code before the type check. On the other hand I don't mind too much myself if there was no type checking for that.

2021-04-27 08:09 UTC, fredericbarthelet commented
@aliclark I'll close this PR for the moment. I opened an issue related to serverless plugins specific definition :)
Thanks for your feedback!

2021-04-27 08:09 UTC, closed without merging